# Generated by Django 5.0.6 on 2024-05-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='looking_for',
            field=models.TextField(null=True),
        ),
    ]
