# Generated by Django 5.0.6 on 2024-05-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkr', '0003_usersubscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscribe',
            name='user_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='usersubscribe',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usersubscribe',
            name='valid_until',
            field=models.DateTimeField(default=None),
        ),
    ]
