# Generated by Django 5.0.6 on 2024-05-15 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vkr', '0005_remove_usersubscribe_id_alter_usersubscribe_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscribe',
            old_name='user_name',
            new_name='username',
        ),
    ]
