# Generated by Django 5.0.6 on 2024-05-15 23:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkr', '0007_remove_usersubscribe_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMembers',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('enjoy_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
