# Generated by Django 5.0.6 on 2024-05-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkr', '0009_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_price',
            field=models.IntegerField(default=1000),
        ),
    ]
