# Generated by Django 5.0.6 on 2024-05-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkr', '0011_eventmembers_user_prof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmembers',
            old_name='event_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='eventmembers',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='eventmembers',
            name='user_prof',
        ),
        migrations.AddField(
            model_name='eventmembers',
            name='event',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='eventmembers',
            name='user',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
