# Generated by Django 5.0.6 on 2024-06-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkr', '0015_alter_usersubscribe_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='', upload_to='events'),
        ),
    ]
