# Generated by Django 5.0.6 on 2024-06-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkr', '0017_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='event_default.png', upload_to='post_pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='event_default.png', upload_to='event_pics'),
        ),
    ]
